### ISSUE TITLE
Add user access control logic and interface

### ISSUE THREAD

**Issue by hexacyanide** [sdevgroup/game-client#1]
The client should be able to authenticate user credentials against the instance server in order to access restricted data. A user should not be able to begin a game instance without authorizing against the server, or playing as an unauthenticated, anonymous user.

The bare minimum for this should be a login dialogue with basic error handling for when a sign-on fails. Additional styling and modifications can also be considered afterwards.

**Comment by MDXiao** [comment]
I was able to create a login screen, the C# socket code will be finished in the next 2 days.

**Comment by MDXiao** [comment]
C# socket code added into the client, game currently has a login screen to identify users. User has to input a name that doesn't already exist in the game.
